# Generated by Django 2.2.13 on 2020-11-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201101_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(default='Not Shared', max_length=10),
        ),
    ]
